### ISSUE TITLE
Anonymous file upload fails (only when Upload button clicked)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/webform#146] opened 2019-05-14 21:58 UTC
I have a webform with a file component.
This form is intended for anonymous users to submit. 
<img width="564" alt="Screen Shot 2019-05-14 at 3 02 28 PM" src="https://user-images.githubusercontent.com/397895/57735387-45662600-7659-11e9-9b3d-efe70ad7cdc4.png">

When they add an image, do not click "Upload", and submit the form, everything works as expected. The image uploads without an issue.

If, however, the add an image, and click "Upload", they will see a link to the file instead of the upload box, but when they later submit the form, the file field fails with the error `[File] field is required.`
<img width="1468" alt="Screen Shot 2019-05-14 at 3 28 45 PM" src="https://user-images.githubusercontent.com/397895/57736484-fde19900-765c-11e9-80b2-c7e03dfd261e.png">

The upload button works perfectly for authenticated users.

**Comment by jenlampton** [comment] 2019-05-14 22:03
I checked core to see if this was a problem with anonymous file uploads, but neither the file field or image field widgets have an `Upload` button:
<img width="868" alt="Screen Shot 2019-05-14 at 3 02 01 PM" src="https://user-images.githubusercontent.com/397895/57735422-60d13100-7659-11e9-980c-8e8a892544af.png">

I do see the button in the definition of the [managed_file form API element](https://api.backdropcms.org/api/backdrop/core%21modules%21file%21file.module/function/file_managed_file_process/1) though.

**Comment by herbdool** [comment] 2019-06-17 20:38
In core perhaps the button was removed to automatically upload when it's chosen.

I can confirm the error. First would be to fix the upload button. Second would be to get rid of the upload button and have it upload automatically.

**Comment by klonos** [comment] 2020-10-14 12:04
> In core perhaps the button was removed to automatically upload when it's chosen.

Yup, that's what we did in https://github.com/backdrop/backdrop-issues/issues/1199 with https://github.com/backdrop/backdrop/pull/1275 

The issue reported here was mentioned in our forum: https://forum.backdropcms.org/forum/image-upload-temporary

A user pointed out similar issues with the Webform 7.x module: https://www.drupal.org/project/webform/issues/2703299#comment-11113879

Hope all this helps.

**Comment by herbdool** [comment] 2021-03-19 15:11
Thanks for reporting the bug @jenlampton and the context @klonos. I think I'll finally fix this by removing the upload button. It's interesting that in d7 the maintainer says it seems to be a core issue. But I'm not sure then why the upload button still appears in Backdrop Webform when it no longer appears in Backdrop core. I'll see.

**Comment by herbdool** [comment] 2021-03-19 20:12
I haven't fixed it but I've got it uploading automatically by ensuring the file.js library is attached to the element. So there's something else going on with sessions and anonymous users.

**Comment by herbdool** [comment] 2021-03-19 21:14
I think this issue may help us here https://www.drupal.org/project/webform/issues/2675170

**Comment by herbdool** [comment] 2021-05-25 20:08
I'm having a hard time tracking this down. It might be a change in core (compared to d7) but I don't know where yet. In `webform_client_form_pages()` the `fid` isn't available (except for the `#conditional_values` array for some reason). It may be further back in `backdrop_process_form()` or such.

Anonymous users, no matter the permissions given, cannot click the Upload button and have the file saved. It'll only work if only selecting and not uploading before the submit. For authenticated users either works.

**Comment by herbdool** [comment] 2021-06-04 18:58
Actually this helps: https://www.drupal.org/project/drupal/issues/2678822. Though funnily it doesn't seem to be needed in Backdrop core, or maybe I'm not testing it properly to see if there is a bug (I created a content type with a file field which anonymous could submit.).

I might create a PR for Webform so it can benefit from a fix and I'll make sure that if/when there's a core change that it will use that instead.

[Update: core does have a bug that the PR fixes after all. Just disable the loading of the JS which automatically uploads the file.]

**Comment by herbdool** [comment] 2021-06-04 20:34
@jenlampton I've created a PR here but I think it's better to get it into core since I've confirmed that it's also a problem there: https://github.com/backdrop/backdrop-issues/issues/1678

**Comment by herbdool** [comment] 2021-06-07 18:29
I'm thinking of making the fix in Webform while we figure out if the fix should go in core too. @jenlampton @laryn are you interested in testing this PR?

**Comment by herbdool** [comment] 2021-08-12 00:46
The PR for core is now fully working so I'll likely close the PR here.

**Comment by herbdool** [comment] 2021-08-13 15:35
backdrop/backdrop#3642 has now been merged into 1.x and 1.19.x and released with 1.19.3. I've adapted the PR so it only includes the core file.js so the file is automatically uploaded.

**Closed as completed** 2021-08-13 15:35 UTC
Labels: has Pull Request
